[2020-09-20 16:02:32,653] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: dag_prueba.prueba_python 2020-08-06T00:00:00+00:00 [queued]>
[2020-09-20 16:02:32,669] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: dag_prueba.prueba_python 2020-08-06T00:00:00+00:00 [queued]>
[2020-09-20 16:02:32,670] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-09-20 16:02:32,670] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2020-09-20 16:02:32,670] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-09-20 16:02:32,676] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): prueba_python> on 2020-08-06T00:00:00+00:00
[2020-09-20 16:02:32,678] {standard_task_runner.py:53} INFO - Started process 24267 to run task
[2020-09-20 16:02:32,765] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: dag_prueba.prueba_python 2020-08-06T00:00:00+00:00 [running]> b349191ed544
[2020-09-20 16:02:32,779] {logging_mixin.py:112} INFO - hello
[2020-09-20 16:02:32,779] {logging_mixin.py:112} INFO - world
[2020-09-20 16:02:32,779] {python_operator.py:114} INFO - Done. Returned value was: None
[2020-09-20 16:02:32,786] {taskinstance.py:1065} INFO - Marking task as SUCCESS.dag_id=dag_prueba, task_id=prueba_python, execution_date=20200806T000000, start_date=20200920T160232, end_date=20200920T160232
[2020-09-20 16:02:42,659] {logging_mixin.py:112} INFO - [2020-09-20 16:02:42,659] {local_task_job.py:103} INFO - Task exited with return code 0
